### ISSUE TITLE
Error:(25, 13) Failed to resolve: top.wuhaojie:scrollnumber:1.0.0 

### ISSUE THREAD

**Issue by jp1017** [a-voyager/ScrollNumber#2]
没上传到仓库吗？

**Comment by a-voyager** [comment]
已经merge，多谢了

**Comment by jp1017** [comment]
@a-voyager 哈哈，没什么的，但是 gradle 添加

```
compile 'top.wuhaojie:scrollnumber:1.0.0'
```

依然找不到库，只能 `compile project(':library')`  使用

项目没上传到 maven 仓库吗，麻烦上传确认下吧

**Comment by a-voyager** [comment]
我试了下，确实存在问题，但仓库显示有这个，我目前也不清楚原因，实在抱歉了，我尽快修复！

**Comment by jp1017** [comment]
可以升级下版本，再次上传到仓库
