### ISSUE TITLE
padding

### ISSUE THREAD

**Issue by vladlen2010** [a-voyager/ScrollNumber#5]
Hello, why does "0" have paddings bigger, than other digits?
<a href='https://postimg.org/image/6vsu54pmp/' target='_blank'><img src='https://s32.postimg.org/6vsu54pmp/image.png' border='0' alt='postimage'/></a>

**Comment by a-voyager** [comment]
Well, maybe because the font itself. I open the font on Windows, it shows as the image.
<a href='http://7xqdz8.com1.z0.glb.clouddn.com/160801font.png' target='_blank'><img src='http://7xqdz8.com1.z0.glb.clouddn.com/160801font.png' border='0' alt='postimage'/></a>

**Comment by vladlen2010** [comment]
No, i think error in this method

canvas.translate(0, mOffset * getMeasuredHeight());

because i comment this line and digits haven't paddings

**Comment by vladlen2010** [comment]
repair this method please

**Comment by a-voyager** [comment]
This bug has fixed. It's because of a method's call order. This is my careless.
