### ISSUE TITLE
内容只支持整型吗？

### ISSUE THREAD

**Issue by bleedyao** [a-voyager/ScrollNumber#9]
开发者你好，我希望在控件中显示小数的滚动效果，但好像目前只支持整型，不知道有没有浮点型数字的接口，如果没有，后面是否会加入，感谢开发者。

**Comment by a-voyager** [comment]
我会考虑尽量加上，谢谢你的建议

**Comment by a-voyager** [comment]
Api 已加上，支持 Double 类型
